// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.WebControls;


namespace ClintonFrankland
{


    public partial class Data
    {

        /// <summary>
    /// litMain control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private Literal _litMain;

        protected virtual Literal litMain
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _litMain;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                _litMain = value;
            }
        }
    }
}