// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated. 
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;
using System.Web.UI.HtmlControls;
using System.Web.UI.WebControls;


namespace ClintonFrankland
{


    public partial class Login
    {

        /// <summary>
    /// hidReturn control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private HiddenField _hidReturn;

        protected virtual HiddenField hidReturn
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _hidReturn;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                _hidReturn = value;
            }
        }

        /// <summary>
    /// divWarning control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private HtmlGenericControl _divWarning;

        protected virtual HtmlGenericControl divWarning
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _divWarning;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                _divWarning = value;
            }
        }

        /// <summary>
    /// inputUsername control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private TextBox _inputUsername;

        protected virtual TextBox inputUsername
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _inputUsername;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                _inputUsername = value;
            }
        }

        /// <summary>
    /// inputPassword control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private TextBox _inputPassword;

        protected virtual TextBox inputPassword
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _inputPassword;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                _inputPassword = value;
            }
        }

        /// <summary>
    /// btnSignin control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        private Button _btnSignin;

        protected virtual Button btnSignin
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _btnSignin;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                if (_btnSignin != null)
                {
                    _btnSignin.Click -= btnSignin_Click;
                }

                _btnSignin = value;
                if (_btnSignin != null)
                {
                    _btnSignin.Click += btnSignin_Click;
                }
            }
        }
    }
}