// <auto-generated />
using System;
using ClintonFrankland.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClintonFrankland.Migrations
{
    [DbContext(typeof(ClintonFranklandDbContext))]
    [Migration("20260807161728_AddActiveBudgetAndDefaultAccountRules")]
    partial class AddActiveBudgetAndDefaultAccountRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AccountName");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("AccountNumber");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int")
                        .HasColumnName("AccountTypeID");

                    b.Property<decimal?>("AvailableCredit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("AvailableCredit");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Balance");

                    b.Property<decimal>("BeginningBalance")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("BeginningBalance");

                    b.Property<decimal>("ClearedBalance")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("ClearedBalance");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("CreditLimit");

                    b.Property<int?>("DueDate")
                        .HasColumnType("int")
                        .HasColumnName("DueDate");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("InterestRate");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("IsDefault");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdated");

                    b.Property<decimal?>("MinimumPayment")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("MinimumPayment");

                    b.Property<int?>("SharedBudgetId")
                        .HasColumnType("int")
                        .HasColumnName("SharedBudgetId");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("WebURL");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("UserId");

                    b.ToTable("cfAccounts");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.AccountType", b =>
                {
                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int")
                        .HasColumnName("AccountTypeId");

                    b.Property<string>("AccountTypeName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("AccountTypeName");

                    b.HasKey("AccountTypeId");

                    b.ToTable("cfAccountTypes");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.AuthLoginAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("AttemptedAtUtc");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ClientIp");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Reason");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit")
                        .HasColumnName("Succeeded");

                    b.Property<string>("UserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAtUtc");

                    b.HasIndex("UserName");

                    b.ToTable("cfAuthLoginAudit");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.BillDueNotificationSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int>("DueSoonDays")
                        .HasColumnType("int")
                        .HasColumnName("DueSoonDays");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsEnabled");

                    b.Property<bool>("PastDueEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("PastDueEnabled");

                    b.Property<int>("PastDueMaxDays")
                        .HasColumnType("int")
                        .HasColumnName("PastDueMaxDays");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAtUtc");

                    b.HasKey("Id");

                    b.ToTable("cfBillDueNotificationSettings");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BudgetId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Amount");

                    b.Property<string>("BudgetName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BudgetName");

                    b.Property<int>("BudgetTypeId")
                        .HasColumnType("int")
                        .HasColumnName("BudgetTypeID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<int?>("FrequencyId")
                        .HasColumnType("int")
                        .HasColumnName("FrequencyID");

                    b.Property<bool?>("IsAutomatic")
                        .HasColumnType("bit")
                        .HasColumnName("IsAutomatic");

                    b.Property<bool?>("IsBill")
                        .HasColumnType("bit")
                        .HasColumnName("IsBill");

                    b.Property<bool?>("IsLate")
                        .HasColumnType("bit")
                        .HasColumnName("IsLate");

                    b.Property<bool>("IsSpendingAllowance")
                        .HasColumnType("bit")
                        .HasColumnName("IsSpendingAllowance");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NextDueDate");

                    b.Property<int?>("PayeeId")
                        .HasColumnType("int")
                        .HasColumnName("PayeeId");

                    b.Property<int?>("SharedBudgetId")
                        .HasColumnType("int")
                        .HasColumnName("SharedBudgetId");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("BudgetId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FrequencyId");

                    b.HasIndex("PayeeId");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("UserId");

                    b.ToTable("cfBudgets");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.BudgetInvite", b =>
                {
                    b.Property<int>("BudgetInviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BudgetInviteId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetInviteId"));

                    b.Property<DateTime?>("AcceptedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("AcceptedAtUtc");

                    b.Property<int?>("AcceptedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("AcceptedByUserId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiresAtUtc");

                    b.Property<string>("InviteTokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("InviteTokenHash");

                    b.Property<int>("InvitedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("InvitedByUserId");

                    b.Property<string>("InviteeEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("InviteeEmail");

                    b.Property<string>("InviteeUserName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("InviteeUserName");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("RevokedAtUtc");

                    b.Property<int?>("RevokedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("RevokedByUserId");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Role");

                    b.Property<int>("SharedBudgetId")
                        .HasColumnType("int")
                        .HasColumnName("SharedBudgetId");

                    b.HasKey("BudgetInviteId");

                    b.HasIndex("InviteTokenHash")
                        .IsUnique();

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("SharedBudgetId", "ExpiresAtUtc");

                    b.ToTable("cfBudgetInvites");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.BudgetMember", b =>
                {
                    b.Property<int>("BudgetMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BudgetMemberId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetMemberId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<DateTime?>("RemovedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("RemovedAtUtc");

                    b.Property<int?>("RemovedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("RemovedByUserId");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Role");

                    b.Property<int>("SharedBudgetId")
                        .HasColumnType("int")
                        .HasColumnName("SharedBudgetId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("BudgetMemberId");

                    b.HasIndex("UserId");

                    b.HasIndex("SharedBudgetId", "UserId")
                        .IsUnique();

                    b.ToTable("cfBudgetMembers");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CategoryName");

                    b.Property<int?>("SharedBudgetId")
                        .HasColumnType("int")
                        .HasColumnName("SharedBudgetId");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("CategoryId");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("UserId");

                    b.ToTable("cfCategories");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.CategoryBudgetTarget", b =>
                {
                    b.Property<int>("CategoryBudgetTargetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryBudgetTargetId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryBudgetTargetId"));

                    b.Property<DateOnly>("BudgetMonth")
                        .HasColumnType("date")
                        .HasColumnName("BudgetMonth");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("PlannedAmount");

                    b.Property<int?>("SharedBudgetId")
                        .HasColumnType("int")
                        .HasColumnName("SharedBudgetId");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAtUtc");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("CategoryBudgetTargetId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SharedBudgetId", "CategoryId", "BudgetMonth")
                        .IsUnique()
                        .HasFilter("[SharedBudgetId] IS NOT NULL");

                    b.HasIndex("UserId", "CategoryId", "BudgetMonth")
                        .IsUnique();

                    b.ToTable("cfCategoryBudgetTargets");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Frequency", b =>
                {
                    b.Property<int>("FrequencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FrequencyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrequencyId"));

                    b.Property<string>("FrequencyName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("FrequencyName");

                    b.Property<int?>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Sort");

                    b.HasKey("FrequencyId");

                    b.ToTable("cfFrequencies");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.MigrationError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MigrationName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("MigrationErrors");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.NotificationSendLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BudgetId")
                        .HasColumnType("int")
                        .HasColumnName("BudgetId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("ErrorMessage");

                    b.Property<DateTime>("NoticeLocalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NoticeLocalDate");

                    b.Property<string>("NoticeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("NoticeType");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Recipient");

                    b.Property<int?>("SharedBudgetId")
                        .HasColumnType("int")
                        .HasColumnName("SharedBudgetId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("Status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Subject");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("UserId", "BudgetId", "NoticeType", "NoticeLocalDate")
                        .IsUnique()
                        .HasFilter("[BudgetId] IS NOT NULL");

                    b.ToTable("cfNotificationSendLog");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Payee", b =>
                {
                    b.Property<int>("PayeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PayeeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayeeId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("PayeeName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("PayeeName");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("PayeeId");

                    b.HasIndex("UserId");

                    b.ToTable("cfPayees");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.PlaidAccountMapping", b =>
                {
                    b.Property<int>("PlaidAccountMappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaidAccountMappingId"));

                    b.Property<int>("BudgetAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlaidAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("PlaidItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("PlaidAccountMappingId");

                    b.HasIndex("BudgetAccountId")
                        .IsUnique();

                    b.HasIndex("PlaidItemId", "PlaidAccountId")
                        .IsUnique();

                    b.ToTable("cfPlaidAccountMappings");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.PlaidItem", b =>
                {
                    b.Property<int>("PlaidItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaidItemId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DisconnectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("InstitutionName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TransactionsCursor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PlaidItemId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("cfPlaidItems");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.PlaidSyncRun", b =>
                {
                    b.Property<int>("PlaidSyncRunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaidSyncRunId"));

                    b.Property<int>("AddedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CursorAfter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CursorBefore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("ModifiedCount")
                        .HasColumnType("int");

                    b.Property<int>("PlaidItemId")
                        .HasColumnType("int");

                    b.Property<int>("RemovedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("PlaidSyncRunId");

                    b.HasIndex("PlaidItemId");

                    b.ToTable("cfPlaidSyncRuns");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.PlaidTransactionStaging", b =>
                {
                    b.Property<int>("PlaidTransactionStagingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaidTransactionStagingId"));

                    b.Property<int>("BudgetAccountId")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPending")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRemoved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkedSourceFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("LinkedTransactionId")
                        .HasColumnType("int");

                    b.Property<string>("MerchantEntityId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PendingTransactionId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PlaidAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("PlaidAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("PlaidItemId")
                        .HasColumnType("int");

                    b.Property<string>("PlaidTransactionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ReviewState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PlaidTransactionStagingId");

                    b.HasIndex("LinkedTransactionId")
                        .IsUnique()
                        .HasFilter("[LinkedTransactionId] IS NOT NULL");

                    b.HasIndex("PlaidItemId", "PlaidTransactionId")
                        .IsUnique();

                    b.HasIndex("UserId", "BudgetAccountId");

                    b.ToTable("cfPlaidTransactionStaging");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.PlaidWebhookDelivery", b =>
                {
                    b.Property<int>("PlaidWebhookDeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaidWebhookDeliveryId"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ItemId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ProcessingStartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("QueuedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("WebhookType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("PlaidWebhookDeliveryId");

                    b.HasIndex("DeliveryKey")
                        .IsUnique();

                    b.HasIndex("Status", "ProcessingStartedAtUtc");

                    b.ToTable("cfPlaidWebhookDeliveries");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.SharedBudget", b =>
                {
                    b.Property<int>("SharedBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SharedBudgetId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SharedBudgetId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAtUtc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("Name");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("int")
                        .HasColumnName("OwnerUserId");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAtUtc");

                    b.HasKey("SharedBudgetId");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("cfSharedBudgets");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.SmtpSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<bool>("AllowInvalidCerts")
                        .HasColumnType("bit")
                        .HasColumnName("AllowInvalidCerts");

                    b.Property<string>("FromName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("FromName");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsEnabled");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("SenderEmail");

                    b.Property<string>("TestRecipientEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TestRecipientEmail");

                    b.Property<int>("TlsMode")
                        .HasColumnType("int")
                        .HasColumnName("TlsMode");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAtUtc");

                    b.HasKey("Id");

                    b.ToTable("cfSmtpSettings");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountId");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(9, 2)")
                        .HasColumnName("Amount");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AttachmentPath");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<bool>("Cleared")
                        .HasColumnType("bit")
                        .HasColumnName("Cleared");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Notes");

                    b.Property<int>("PayeeId")
                        .HasColumnType("int")
                        .HasColumnName("PayeeId");

                    b.Property<int?>("SharedBudgetId")
                        .HasColumnType("int")
                        .HasColumnName("SharedBudgetId");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("TransactionDate");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PayeeId");

                    b.HasIndex("SharedBudgetId");

                    b.HasIndex("UserId");

                    b.ToTable("cfTransactions");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.TransactionRule", b =>
                {
                    b.Property<int>("TransactionRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionRuleId"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("ApprovalState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("approved");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("ContainsText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EvidenceSummary")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatchCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaximumAmount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("MerchantEntityId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("MinimumAmount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("NormalizedMerchant")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PayeeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("manual");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TransactionRuleId");

                    b.HasIndex("UserId", "Priority");

                    b.HasIndex("UserId", "AccountId", "MerchantEntityId");

                    b.ToTable("cfTransactionRules");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<int?>("ActiveSharedBudgetId")
                        .HasColumnType("int")
                        .HasColumnName("ActiveSharedBudgetId");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("ExternalDisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ExternalDisplayName");

                    b.Property<string>("ExternalEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ExternalEmail");

                    b.Property<string>("ExternalProvider")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ExternalProvider");

                    b.Property<string>("ExternalSubject")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("ExternalSubject");

                    b.Property<DateTime>("FirstLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("FirstLogin");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("IsAdmin");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastExternalLoginUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastExternalLoginUtc");

                    b.Property<string>("LastIPAddress")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("LastIPAddress");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastLogin");

                    b.Property<bool>("ListButtonsRight")
                        .HasColumnType("bit")
                        .HasColumnName("ListButtonsRight");

                    b.Property<TimeOnly>("NotificationDeliveryTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValue(new TimeOnly(8, 0, 0))
                        .HasColumnName("NotificationDeliveryTime");

                    b.Property<string>("NotificationTimezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("America/New_York")
                        .HasColumnName("NotificationTimezone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<DateTime?>("PasswordResetRequestOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("PasswordResetRequestOn");

                    b.Property<Guid?>("PasswordResetToken")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PasswordResetToken");

                    b.Property<bool>("ReceiveBillDueNotices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ReceiveBillDueNotices");

                    b.Property<bool>("ReceiveWeeklyUpcomingBillDigest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ReceiveWeeklyUpcomingBillDigest");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Salt");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("UserName");

                    b.HasKey("UserId");

                    b.HasIndex("ExternalProvider", "ExternalSubject")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [ExternalProvider] IS NOT NULL AND [ExternalSubject] IS NOT NULL");

                    b.ToTable("cfUsers");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Account", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.SharedBudget", "SharedBudget")
                        .WithMany("Accounts")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClintonFrankland.Models.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccountType");

                    b.Navigation("SharedBudget");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Budget", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.Category", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.Frequency", "Frequency")
                        .WithMany("Budgets")
                        .HasForeignKey("FrequencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClintonFrankland.Models.Entities.Payee", "Payee")
                        .WithMany("Budgets")
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClintonFrankland.Models.Entities.SharedBudget", "SharedBudget")
                        .WithMany("Budgets")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClintonFrankland.Models.Entities.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Frequency");

                    b.Navigation("Payee");

                    b.Navigation("SharedBudget");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.BudgetInvite", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.User", "InvitedByUser")
                        .WithMany("SentBudgetInvites")
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.SharedBudget", "SharedBudget")
                        .WithMany("Invites")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("SharedBudget");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.BudgetMember", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.SharedBudget", "SharedBudget")
                        .WithMany("Members")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.User", "User")
                        .WithMany("BudgetMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SharedBudget");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Category", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.SharedBudget", "SharedBudget")
                        .WithMany("Categories")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClintonFrankland.Models.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SharedBudget");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.CategoryBudgetTarget", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.Category", "Category")
                        .WithMany("CategoryBudgetTargets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.SharedBudget", "SharedBudget")
                        .WithMany("CategoryBudgetTargets")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClintonFrankland.Models.Entities.User", "User")
                        .WithMany("CategoryBudgetTargets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SharedBudget");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Payee", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.User", "User")
                        .WithMany("Payees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.PlaidAccountMapping", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.Account", "BudgetAccount")
                        .WithMany()
                        .HasForeignKey("BudgetAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.PlaidItem", "PlaidItem")
                        .WithMany("AccountMappings")
                        .HasForeignKey("PlaidItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BudgetAccount");

                    b.Navigation("PlaidItem");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.PlaidItem", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.User", "User")
                        .WithMany("PlaidItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.SharedBudget", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.User", "OwnerUser")
                        .WithMany("OwnedSharedBudgets")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Transaction", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.Payee", "Payee")
                        .WithMany("Transactions")
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.SharedBudget", "SharedBudget")
                        .WithMany("Transactions")
                        .HasForeignKey("SharedBudgetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClintonFrankland.Models.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Payee");

                    b.Navigation("SharedBudget");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Category", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("CategoryBudgetTargets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Frequency", b =>
                {
                    b.Navigation("Budgets");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Payee", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.PlaidItem", b =>
                {
                    b.Navigation("AccountMappings");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.SharedBudget", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Budgets");

                    b.Navigation("Categories");

                    b.Navigation("CategoryBudgetTargets");

                    b.Navigation("Invites");

                    b.Navigation("Members");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("BudgetMemberships");

                    b.Navigation("Budgets");

                    b.Navigation("Categories");

                    b.Navigation("CategoryBudgetTargets");

                    b.Navigation("OwnedSharedBudgets");

                    b.Navigation("Payees");

                    b.Navigation("PlaidItems");

                    b.Navigation("SentBudgetInvites");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
