// <auto-generated />
using System;
using ClintonFrankland.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClintonFrankland.Migrations
{
    [DbContext(typeof(ClintonFranklandDbContext))]
    [Migration("20260308161153_AddNotesAndAttachmentToTransaction")]
    partial class AddNotesAndAttachmentToTransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AccountName");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("AccountNumber");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int")
                        .HasColumnName("AccountTypeID");

                    b.Property<decimal?>("AvailableCredit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("AvailableCredit");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Balance");

                    b.Property<decimal>("BeginningBalance")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("BeginningBalance");

                    b.Property<decimal>("ClearedBalance")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("ClearedBalance");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("CreditLimit");

                    b.Property<int?>("DueDate")
                        .HasColumnType("int")
                        .HasColumnName("DueDate");

                    b.Property<decimal?>("InterestRate")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("InterestRate");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit")
                        .HasColumnName("IsDefault");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdated");

                    b.Property<decimal?>("MinimumPayment")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("MinimumPayment");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("WebURL");

                    b.HasKey("AccountId");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("cfAccounts");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.AccountType", b =>
                {
                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int")
                        .HasColumnName("AccountTypeId");

                    b.Property<string>("AccountTypeName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("AccountTypeName");

                    b.HasKey("AccountTypeId");

                    b.ToTable("cfAccountTypes");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.AuthLoginAudit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttemptedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("AttemptedAtUtc");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("ClientIp");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Reason");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit")
                        .HasColumnName("Succeeded");

                    b.Property<string>("UserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAtUtc");

                    b.HasIndex("UserName");

                    b.ToTable("cfAuthLoginAudit");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BudgetId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BudgetId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Amount");

                    b.Property<string>("BudgetName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("BudgetName");

                    b.Property<int>("BudgetTypeId")
                        .HasColumnType("int")
                        .HasColumnName("BudgetTypeID");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<int?>("FrequencyId")
                        .HasColumnType("int")
                        .HasColumnName("FrequencyID");

                    b.Property<bool?>("IsAutomatic")
                        .HasColumnType("bit")
                        .HasColumnName("IsAutomatic");

                    b.Property<bool?>("IsBill")
                        .HasColumnType("bit")
                        .HasColumnName("IsBill");

                    b.Property<bool?>("IsLate")
                        .HasColumnType("bit")
                        .HasColumnName("IsLate");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NextDueDate");

                    b.Property<int?>("PayeeId")
                        .HasColumnType("int")
                        .HasColumnName("PayeeId");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("BudgetId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FrequencyId");

                    b.HasIndex("PayeeId");

                    b.HasIndex("UserId");

                    b.ToTable("cfBudgets");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CategoryName");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("cfCategories");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Frequency", b =>
                {
                    b.Property<int>("FrequencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FrequencyId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrequencyId"));

                    b.Property<string>("FrequencyName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("FrequencyName");

                    b.Property<int?>("Sort")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("Sort");

                    b.HasKey("FrequencyId");

                    b.ToTable("cfFrequencies");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Payee", b =>
                {
                    b.Property<int>("PayeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PayeeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayeeId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("PayeeName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("PayeeName");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("PayeeId");

                    b.HasIndex("UserId");

                    b.ToTable("cfPayees");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.SmtpSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<bool>("AllowInvalidCerts")
                        .HasColumnType("bit")
                        .HasColumnName("AllowInvalidCerts");

                    b.Property<string>("FromName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("FromName");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("IsEnabled");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("SenderEmail");

                    b.Property<string>("TestRecipientEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("TestRecipientEmail");

                    b.Property<int>("TlsMode")
                        .HasColumnType("int")
                        .HasColumnName("TlsMode");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAtUtc");

                    b.HasKey("Id");

                    b.ToTable("cfSmtpSettings");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountId");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(9, 2)")
                        .HasColumnName("Amount");

                    b.Property<string>("AttachmentPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AttachmentPath");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<bool>("Cleared")
                        .HasColumnType("bit")
                        .HasColumnName("Cleared");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Notes");

                    b.Property<int>("PayeeId")
                        .HasColumnType("int")
                        .HasColumnName("PayeeId");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("TransactionDate");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PayeeId");

                    b.HasIndex("UserId");

                    b.ToTable("cfTransactions");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("EmailAddress");

                    b.Property<DateTime>("FirstLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("FirstLogin");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit")
                        .HasColumnName("IsAdmin");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("LastIPAddress")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("LastIPAddress");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastLogin");

                    b.Property<bool>("ListButtonsRight")
                        .HasColumnType("bit")
                        .HasColumnName("ListButtonsRight");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("PasswordHash");

                    b.Property<DateTime?>("PasswordResetRequestOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("PasswordResetRequestOn");

                    b.Property<Guid?>("PasswordResetToken")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PasswordResetToken");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Salt");

                    b.Property<int>("SiteId")
                        .HasColumnType("int")
                        .HasColumnName("SiteId");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("UserName");

                    b.HasKey("UserId");

                    b.ToTable("cfUsers");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Account", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.AccountType", "AccountType")
                        .WithMany("Accounts")
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccountType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Budget", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.Category", "Category")
                        .WithMany("Budgets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.Frequency", "Frequency")
                        .WithMany("Budgets")
                        .HasForeignKey("FrequencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClintonFrankland.Models.Entities.Payee", "Payee")
                        .WithMany("Budgets")
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ClintonFrankland.Models.Entities.User", "User")
                        .WithMany("Budgets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Frequency");

                    b.Navigation("Payee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Category", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Payee", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.User", "User")
                        .WithMany("Payees")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Transaction", b =>
                {
                    b.HasOne("ClintonFrankland.Models.Entities.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.Payee", "Payee")
                        .WithMany("Transactions")
                        .HasForeignKey("PayeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClintonFrankland.Models.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Payee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.AccountType", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Category", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Frequency", b =>
                {
                    b.Navigation("Budgets");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.Payee", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ClintonFrankland.Models.Entities.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Budgets");

                    b.Navigation("Categories");

                    b.Navigation("Payees");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
